### ISSUE TITLE
Changing the labels

### ISSUE THREAD

**Issue by noesteijver** [jahvi/post-category-filter#2]
I've just installed the plugin and tested it, and it works very nice!

The placeholder text of the input field is always 'Filter Categories'. Is it possible to change Categories to the taxonomy name of the taxonomy that is used? That would be a very nice addition!

Hopefully this will be added in the future. If I can help, let me know!

Greetings,
-Kevin

**Comment by jahvi** [comment]
This will probably be added in a future version, it's a tricky one so it might take a while

**Comment by noesteijver** [comment]
Maybe, for universal purposes, it's better to rename this label to 'terms' instead of 'categories'. 

Can't go wrong with that term ;-)

**Comment by jahvi** [comment]
Labels now show as "Filter {taxonomy name}" as of 5d4e92 😄 

Feel free to update to the latest version and report any issues.
